# Aplicación de Random forest
Explicación de Random forest

```{r}
set.seed(123)
# install.packages("randomForest")
library(randomForest)
# install.packages("caTools")
library(caTools)
library("caret")
# library("klaR")
```


Cargamos los datos de entrenamiento y de pruebas preprocesados (Ver notebook data_analysis.Rmd)


```{r}
train <- read.csv("dataset/train_preprocessed.data", sep=",", row.names=NULL, header=TRUE)
head(train)
dim(train)

test <- read.csv("dataset/test_preprocessed.data", sep=",", row.names=NULL, header=TRUE)
head(test)
dim(test)
```

Transformamos los datos (TODO: Explicar)

```{r}
summary(train)
dim(train)	
```

```{r}
transform_data <- function(dataframe) {
    dataframe <- transform(dataframe, age=as.integer(age), workclass=as.factor(workclass),
        fnlwgt=as.numeric(fnlwgt), education=as.factor(education), education_num=as.integer(education_num),
        marital_status=as.factor(marital_status), occupation=as.factor(occupation), relationship=as.factor(relationship),
        race=as.factor(race), sex=as.factor(sex), capital_gain=as.numeric(capital_gain), capital_loss=as.numeric(capital_loss),
        hours_per_week=as.integer(hours_per_week), native_country=as.factor(native_country), target=as.factor(target),
        hours_per_week_categorical=as.factor(hours_per_week_categorical),has_capital_gain=as.factor(has_capital_gain),
        has_capital_loss=as.factor(has_capital_loss)
    )

    return(dataframe)
}
```



```{r}
train <- transform_data(train)
summary(train)	
dim(train)

test <- transform_data(test)
summary(test)
dim(test)
```


```{r}

selected_attributes <- c("age", "fnlwgt", "workclass", "education", "marital_status", "occupation", "relationship", 
"race", "sex", "native_country", "hours_per_week_categorical", "has_capital_gain", "has_capital_loss", "target")

train <- train[selected_attributes]
# y_train <- train$target

test <- test[selected_attributes]
# y_test <- test$target

model_rf <- randomForest(target ~ ., data=train,
    x_test = test[-14],
    y_test = test[14]
# ,
    # ntree=100, 
    # importance=TRUE,
    # mtry = 3.7
)

```

```{r}
# help(randomForest)	
```

```{r}
model_rf
```

```{r}
y_pred_train <- predict(model_rf, new_data = train)

train_precision <- precision(data=y_pred_train, reference=train$target, relevant=">50K")
train_precision
train_recall <- recall(data=y_pred_train, reference=train$target, relevant=">50K")
train_recall
train_f1 <- F_meas(data=y_pred_train, reference=train$target, relevant=">50K")
train_f1
```

```{r}
# help(predict)
summary(test)
```
```{r}
levels(test$native_country) <- levels(train$native_country)
y_pred_test <- predict(model_rf, test)


test_precision <- precision(data=y_pred_test, reference=test$target, relevant=">50K")
test_precision
test_recall <- recall(data=y_pred_test, reference=test$target, relevant=">50K")
test_recall
test_f1 <- F_meas(data=y_pred_test, reference=test$target, relevant=">50K")
test_f1

```

```{r}
# colnames(train)
levels(test$native_country) <- levels(train$native_country)
```	
